### ISSUE TITLE
Compatibility preventing opening setting in Foundry VTT 10

### ISSUE THREAD

**Issue by Kiratomi** [Smashman/table-map-foundryvtt-module#2] opened 2022-09-11 23:30 UTC
I cannot get the Configure Settings menu to open once I have this module running in the updated version 10+ of Foundry VTT. I really like this module and would much prefer to not roll back the version. Is this an issue that only I am having for some reason? I have tested this with several modules turned on, and even if this is the only one running it prevents me from configuring settings so I can set this up properly.

**Comment by Smashman** [comment] 2022-09-14 22:07
Thanks for letting me know, I have not had a chance to upgrade my Foundry version to 10 and so haven't seen this issue. I will take a look tomorrow and let you know!

**Comment by Kiratomi** [comment] 2022-09-14 22:10
That is greatly appreciated! It is the most helpful and I hope it is worth the fix for you! You have made, by far, the best in person map mod for Foundry and I use it for my longtime weekly game. I am saying all of this to say thank you for your hard work!

**Comment by Smashman** [comment] 2022-09-15 12:47
Sadly I'm unable to reproduce this issue locally with a v10 installation. I did come across a compatibility warning, but it shouldn't have caused a failure like you're reporting. Are you able to show me any console errors to help me determine the issue?
Thanks.

**Comment by Kiratomi** [comment] 2022-09-22 14:22
I got that log for you! Sorry to take so long in my response. Thank you again! 

Up top we have Table Map turned off

![Settings - Working](https://user-images.githubusercontent.com/113316583/191772547-4157975f-2c2c-440c-b1f4-7890ce1170d9.png)

And here we have Table Map turned on. 

![Settings - No Work](https://user-images.githubusercontent.com/113316583/191772593-6c446338-de21-4c8f-b5b9-9536e0fa4afd.png)

**Comment by Kiratomi** [comment] 2022-09-22 14:22
I hit the wrong button, clearly not closed..... my apologies.

**Comment by Smashman** [comment] 2022-09-23 10:22
Do you have any other modules enabled?

Does this issue occur if TableMap is the only enabled module?

If not, can you determine the combination of modules that causes this issue? Thanks.

**Comment by Kiratomi** [comment] 2022-09-23 11:27
For that image, it was the only module enabled. Everything is completely updated to the most recent settings as well. 

If this isn't something you can reproduce,  I may need to start looking at uninstalling other modules or reinstalling Foundry fresh.

**Comment by Smashman** [comment] 2022-09-23 15:37
What's the Foundry version and build number that you're currently running?

**Comment by Smashman** [comment] 2022-09-23 16:03
I am unable to reproduce your issue on any version. Please could you reset your settings to default and see if that resolves the issue?

It looks like one of the options is in a state that it shouldn't get to, so I am unsure how you've managed it.

If after resetting your settings you still get the issue, then I will ask to discuss on Discord.

Thanks.

**Comment by SirMotte** [comment] 2022-09-24 22:48
![grafik](https://user-images.githubusercontent.com/82598692/192121244-f1483441-3ccd-4983-8ff2-ea4d86a5c170.png)
I can confirm this happening, even with no other modules active. (5e)
On a newly created world (5e) this does not happen though, so one or another setting must be responsible or a module that was active at some point. Resetting the settings in an established world did not solve the issue.



```
Error: An error occurred while rendering SettingsConfig 57. Setting Model Validation Errors
[Setting.value]: may not be undefined
    at SchemaField._validateType (commons.js:4082:15)
    at SchemaField.validate (commons.js:3809:37)
    at Setting.validate (commons.js:5462:35)
    at new DataModel (commons.js:5239:26)
    at new Document (commons.js:5778:3)
    at new BaseSetting (commons.js:9789:3)
    at new ClientDocumentMixin (foundry.js:12941:5)
    at new Setting (foundry.js:21171:1)
    at ClientSettings.get (foundry.js:2773:21)
    at SettingsConfig._prepareCategoryData (foundry.js:71112:31)
onError @ foundry.js:747
(anonymous) @ foundry.js:5028
Promise.catch (async)
render @ foundry.js:5026
_onSettingsButton @ foundry.js:75848
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```


Edit: Now that I was able to do some testing, it seems there are more things amiss aswell.
All hotkey functionality does not work - I'm testing with Brave Browers which is chrome based.

Just an idea, could this be caused by the new shift + long left mouse button press forced canvas pan?

Haven't done any tests with other browsers yet.

Edit Edit: Seems like the option for inputting UI scaling does not appear at all, this migh be the cause for the hotkeys not working correctly but for full-screen adjustment.

Edit Edit Edit: I wanted to make a screenshot of the options not available, now I'm suddenly confronted with the same error and the options menu not opening.

**Comment by Kiratomi** [comment] 2022-09-24 23:20
I really appreciate you digging so deep into this. If I didn't have a two year deep campaign I would be all in to just start a new world and be done with it. But my players' journals are deep with info haha.

**Comment by SirMotte** [comment] 2022-09-24 23:27
> I really appreciate you digging so deep into this. If I didn't have a two year deep campaign I would be all in to just start a new world and be done with it. But my players' journals are deep with info haha.

In the meantime you could test out [Monks Common Display](https://github.com/ironmonk88/monks-common-display), though I found the screen mirroring not working as well.

**Comment by Nothv13** [comment] 2022-09-29 01:25
I just want to confirm that I too have this issue. It is the only module active and I get the same error. The only difference is in teh first line after it says settingsconfig, mine says 41 instead of 57.

**Comment by SirMotte** [comment] 2022-09-29 03:46
> I just want to confirm that I too have this issue. It is the only module active and I get the same error. The only difference is in teh first line after it says settingsconfig, mine says 41 instead of 57.

A newly released module does just like Monk's Common Display mentioned above have some similar features. Maybe you can try this as well: [Gamin Table](https://github.com/skepickle/foundryvtt-gaming-table-player)

**Comment by Smashman** [comment] 2022-10-01 12:11
I have no way to reproduce this as it doesn't occur on a fresh installation or on my active installation. I'll take another look at it now. I see @SirMotte did attempt reset, but that didn't help. I will see if I can determine a way to export settings so that I can see which has found itself in the error state.

**Comment by SirMotte** [comment] 2022-10-01 12:37
> 

I wasn't aware that bridging a module gap with another module was frowned upon. I'll be sure to not do this here anymore, - or try to contribute to this repository in any way at all. Thank you for making this clear.

**Comment by Smashman** [comment] 2022-10-01 13:20
Good news. I believe that I've cracked the issue! I am just testing now and will release 2.0.0 in the next hour or so.

For those interested, v10 has made setting defaults mandatory and as I wanted to have one of the settings to contain a blank default I left it as `undefined`. I've switched over to using `null` for that setting and I appear to no longer have the issue.

**Comment by Smashman** [comment] 2022-10-01 14:03
New version has been pushed to Foundry!
@Kiratomi, @Nothv13 please could you test and let me know if this has resolved the problem and I will close the issue if you let me know things are good.

Thanks!

**Closed as completed** 2023-10-23 12:57 UTC
